services:
    backend:
        build: ./backend
        ports:
            - '127.0.0.1:8000:8000'
        restart: always
        container_name: backend
        # env_file:
        #   - ./envs/backend.env
    frontend:
        ports:
            - '127.0.0.1:3000:3000'
        restart: always
        container_name: frontend
        depends_on: 
          - backend
        build: ./frontend
        # env_file:
        #   - ./envs/frontend.env
