import localFont from "next/font/local";
import "./globals.css";
import MainProvider from "./provider/main-provider";
import Sidebar from "@/components/layout/Sidebar";
import { Poppins } from "next/font/google";
import { Box } from "@mui/material";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className}`}>
        <MainProvider>
          <Sidebar />
          <Box
            sx={{ width: "calc(100% - 270px)", px: 16 , py : 8 , marginLeft: "auto" }}
            component={"main"}
          >
            {children}
          </Box>
        </MainProvider>
      </body>
    </html>
  );
}
